// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryDemo.business.Data;

namespace RepoDemo.Business.Migrations
{
    [DbContext(typeof(ChatContext))]
    [Migration("20211223094817_seeding")]
    partial class seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RepositoryDemo.business.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "sarah@example.com",
                            Name = "Sarah",
                            PhoneNumber = 635578892
                        },
                        new
                        {
                            Id = 2,
                            Email = "burt@example.com",
                            Name = "Burt",
                            PhoneNumber = 635578893
                        },
                        new
                        {
                            Id = 3,
                            Email = "devon@example.com",
                            Name = "Devon",
                            PhoneNumber = 635578894
                        },
                        new
                        {
                            Id = 4,
                            Email = "oprah@example.com",
                            Name = "Oprah",
                            PhoneNumber = 635578895
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
